### PR TITLE
Set up versioneer

### LINKED ISSUE #47: add versioneer
anyone up for doing this?

### PR DESCRIPTION
**Pull request by laserson**
Fixes #47.

### CODE REVIEW

**Comment by laserson** [comment]
As it stands, `current-release` in `downloads.yml` is being set manually.  We could probably instead import `mhcflurry.__version__` and pull off the leading chunk, but maybe you want to maintain manual control over this?

**Comment by timodonnell** [comment]
Thanks @laserson ! Seems best to keep setting things manually in download.yml since the versions for the downloadable models only change when we retrain them, not for every version update to the code (i.e. many releases change code but not models).

@julia326 @tavinathanson I remember you having opinions on code versioning. Does the versioneer approach in this PR look good to you?

**Comment by tavinathanson** [comment]
This LGTM 👍

**Comment by julia326** [comment]
I've generally walked away from Versioneer a bit, have been setting up repos with the deploy strategy as in `mhcnames` and `topiary` - I've found that works well, but I'm sure Versioneer is good too

**Pull request merged**
