### PR TITLE
Big refactor to prepare for release

### PR DESCRIPTION
**Pull request by timodonnell**
Lazily putting this all in one commit.

* infrastructure for downloading datasets and published trained models (the `mhcflurry-downloads` command)
* docs and scripts (in `downloads-generation`) to generate the pubilshed datsets and trained models
* parallelized cross validation and model training implementation, including support for imputation (based on the old mhcflurry-cloud repo, which is now gone)
* a single front-end script for class1 allele-specific cross validation and model training / testing (`mhcflurry-class1-allele-specific-cv-and-train`)
* refactor how we deal with hyper-parameters and how we instantiate Class1BindingPredictors
* make Class1BindingPredictor pickleable and remove old serialization code
* move code particular to class 1 allele-specific predictors into its own submodule
* remove unused code including arg parsing, plotting, and ensembles
* had to bump the binding prediction threshold for the Titin1 epitope from 500 to 700, as this test was sporadically failing for me (see test_known_class1_epitopes.py)
* Attempt to make tests involving randomness somewhat more reproducible by setting numpy random seed
* update README

### CODE REVIEW

**Comment by timodonnell** [comment]
The Python 2.7 tests on travis are going to fail until I change the published downloadable models to serialize differently but I thought it would be useful to get this out there for code reviewing. I'm currently rerunning model selection so with any luck we will have that fixed soon.

**Comment by iskandr** [comment]
@timodonnell Looks like Travis also fails for Python 3.x with ```nose.proxy.ValueError: Fewer non-zero entries in p than size```

**Comment by timodonnell** [comment]
I was not able to get the allele-specific models to train again with imputation yesterday, but I did get it to work without imputation, which is what this branch is using now. Surprisingly since it did work once before but apparently that was lucky.

I'm going to do more debugging of the parallel model selection with imputation today, but I think we should plan on doing an initial release without imputation and then update it when we have it working consistently.

So, this PR should be ready for review now.

**Comment by iskandr** [comment]
Those imputation errors looked like you had empty alleles (without any
observed data), I remember having to explicitly filter on each fold to make
sure only alleles with sufficient data got included as inputs to MICE.

**Comment by iskandr** [comment]
I aspire to one day change the name "downloads-generation" into something more intuitive (for some reason it makes me think of a robot that downloads all of GenX). 

Other than that, LGTM

**Pull request merged**
