### PR TITLE
Dockerizing (WIP)

### PR DESCRIPTION
**Pull request by maximz**
Dockerized.

Remaining tasks:
* [ ] Split into base box with dependencies
* [ ] Make dev image that mounts code as volume (instead of git cloning)
* [ ] Add CI
* [ ] Build separate `:cpu` and `:gpu` containers

### CODE REVIEW

**Comment by hammer** [comment]
@maximz awesome! can you change the names of the scripts to indicate they're specific to docker?

**Comment by hammer** [comment]
@maximz also think we can make the build one line w/ `docker build -t hammerlab/mhcflurry:latest .`. Would be nice as my `docker tag` doesn't accept `-f` as a flag.

**Comment by maximz** [comment]
`-f` can be removed directly, it's now implicit. Thanks for catching that.

I'll rename and prefix `docker_`.

I think it makes sense to keep our tagging separate from building so we can test the image. Should the CI script be:
```
docker build...
docker run mhcflurry-img nosetests mhcflurry # on error, CI will pause
docker tag...
docker push...
```
or should we run tests from the Dockerfile? (this is for when nosetests are fixed)

**Comment by hammer** [comment]
We should build two images, one from the `:cpu` base and one from the `:gpu` base.

**Comment by hammer** [comment]
I did get a GPU container image working but think we should revisit the base image and not bother including all of the deep learning libraries as the image is quite bloated.

**Comment by iskandr** [comment]
Hey @maximz, how is this branch coming along? Should I review it?

**Comment by maximz** [comment]
@iskandr I haven't been working actively on this, though it looks like @hammer 's gotten mhcflurry working on top of TensorFlow backend in Docker (https://github.com/hammerlab/mhcflurry/issues/38). If so, let's swap out the base box as Jeff suggested above.

@hammer, if you have a working docker configuration, we can turn it into a Dockerfile and put it in this branch. Is that the next step? I can also circle back and hit some of the TODOs above.

**Comment by hammer** [comment]
Yeah I'm happily using my Docker container on the DevBox to train models w/ TensorFlow on the GPU. It's `hammerlab/mhcflurry:gpu` and is a beast (5.696 GB).

I think we should build from the TF images rather than the `floydhub/dl-docker:gpu` image. I haven't gotten around to writing that dockerfile. Some day soon...

**Comment by hammer** [comment]
Also TODO: my current Docker image has TensorFlow and dependencies installed on top of Python 2. We should really install on top of Python 3.

**Comment by timodonnell** [comment]
@hammer Can you point us to your Dockerfile? I don't think I can access it just from the image on docker hub.

I'd like to merge one of these working docker images for MHCflurry into master and set up an automated build on docker hub (may require deleting and recreating the hammerlab/mhcflurry repo on docker hub).

**Comment by hammer** [comment]
@timodonnell i didn't use a dockerfile it's just an image that's on the DevBox

If you want a Dockerfile I'd suggest starting from a leaner image than the one Maxim is starting from as it's quite massive and has a lot of extraneous gunk.

**Comment by iskandr** [comment]
Closing in favor of https://github.com/hammerlab/mhcflurry/pull/45

**Pull request closed without merging**
