### PR TITLE
Added Windows compatibility.

### PR DESCRIPTION
**Pull request by alexanderwhatley**
In the file `mhcflurry/downloads_command.py`, accessing a NamedTemporaryFile in another process cannot be done in Windows. See https://docs.python.org/2/library/tempfile.html#tempfile.mkstemp. I fixed this by using the mkstemp interface instead. Now the `mhcflurry-downloads fetch` command works on Windows too.

### CODE REVIEW

**Comment by timodonnell** [comment]
Thanks for doing this @alexanderwhatley ! It looks like a bunch of formatting changes have slipped in here (perhaps your editor is automatically converting spaces to tabs) -- could you revert those please?

**Comment by alexanderwhatley** [comment]
Sorry about that, I untabified the file and pushed, are you able to see the changes? (Sorry, I'm pretty inexperienced with git.)

**Comment by timodonnell** [comment]
No worries, still looks like there's a bunch of formatting changes though. You can see all the changes you are proposing by clicking the 'Files Changed' tab above

**Comment by alexanderwhatley** [comment]
Ok, I changed it manually, hopefully should be good now.

**Comment by timodonnell** [comment]
Manually integrated these changes into latest MHCflurry 
in commit https://github.com/hammerlab/mhcflurry/commit/503c84924c1dfe939139b7520513c92374e8c44c. @alexanderwhatley let us know if you hit any issues with this. Thanks for the PR!

**Pull request closed without merging**
