### PR TITLE
Fixing code typo: allelle -> allele.

### PR DESCRIPTION
**Pull request by julia326**

### CODE REVIEW

**Comment by timodonnell** [comment]
LGTM thanks @julia326 . Does this option work now?

**Comment by julia326** [comment]
Not yet, just filed an issue about that: #109

**Comment by julia326** [comment]
@timodonnell the option works now - let me know if this is okay to merge, I added a bit to create the output models directory if it doesn't exist

**Comment by timodonnell** [comment]
Sure, LGTM!

**Pull request merged**
